export const getMetadata = async () => {
    return [
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
        {
            categoryName: '',
            metaTitle: '',
            H1: '',
            H2: '',
            metaDescription: '',
            keywords: '',
            region: '',
            role: '',
            industry: '',
            experienceLevel: ''
        },
    ]
}